name: Deploy CFT

on: [push]

jobs:
  website:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install    
      working-directory: frontend
    - name: Build
      run: CI=false npm run-script build
      working-directory: frontend

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy CFT
      id: website-cft
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: website-cft
        template: cft/main.yml
        no-fail-on-empty-changeset: "1"

    - name: Deploy Frontent
      run: aws s3 sync . s3://roland-bernau-resume
      working-directory: frontend/build
