name: Deploy CFT

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

jobs:
  website:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install    
    - name: Build
      run: npm build

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region}}

    - name: Deploy CFT
      id: website-cft
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: website-cft
        template: cft/main.yml
        no-fail-on-empty-changeset: "1"
